[[main]]
  name = "主页"
  url = "/"
  weight = 10

[[main]]
  name = "博客"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "分类"
  pageRef = "categories"
  weight = 20

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "GitHub"
  url = "https://github.com/goimer/"
  weight = 30
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"
    icon = "search"